### ISSUE TITLE
Add upower-nosystemd

### ISSUE THREAD

**Issue by crocket** [arch-openrc/arch-nosystemd#3]
I think I didn't properly communicate the absence of upower-nosystemd in arch-nosystemd in my last issue.

To make xfce4-power-manager work, I had to compile `upower-nosystemd` on my system independently. It'd cool to add it to arch-nosystemd so that efforts are not duplicated by each and every user of arch-openrc.

**Comment by cromerc** [comment]
The biggest issue is that the upstream upower-nosystemd cannot be built. It has dependencies that cannot be met since there are packages that no longer exist in the AUR:
https://aur.archlinux.org/packages/upower-nosystemd

My recommendation is to try to get the author of that PKGBUILD to update it to work, if it is fixed then this could be added in the future.

**Comment by archnous** [comment]
@crocket Have you tried upower-pm-utils from the old [openrc-eudev] repository? It's what I use along with mate-{power,session}-manager-upower.

**Comment by archnous** [comment]
Now, I see in my old [pfkernel] repo two packages of interest: [xfce4-power-manager-upower](https://github.com/aur-archive/xfce4-power-manager-upower) and [xfce4-session-consolekit](https://github.com/aur-archive/xfce4-session-consolekit). Upstream xfce4 packages wouldn't work directly with upower-pm-utils. You could re-upload and maintain them to the AUR just as I do for my MATE ones.

**Comment by cromerc** [comment]
The maintainer of the package has fixed the dependencies, I have now added those dependencies and upower-nosystemd to the repos.
